### ISSUE TITLE
Remover node_modules do versionamento

### ISSUE THREAD

**Issue by wildeee** [gcapoia/MEAN-Project#1]
Capoia, coloca o node_modules no .gitignore, vc já tem todas as dependências no seu package.json, então não tem necessidade de manter eles no versionamento. Dessa forma, pra baixar eles depois é só dar um npm install

**Comment by gcapoia** [comment]
oASKoASK vlw

Em 14 de agosto de 2015 12:34, wildeee <notifications@github.com> escreveu:

> Capoia, coloca o node_modules no .gitignore, vc já tem todas as
> dependências no seu package.json, então não tem necessidade de manter eles
> no versionamento. Dessa forma, pra baixar eles depois é só dar um npm
> install
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gcapoia/MEAN-Project/issues/1>.
>



-- 
ATT
Gabriel Capoia dos Santos
cel.: 9908-7862
